version '3.8'

services:
  backend:
    build: ./backend
    container_name: openrag-backend
    restart: always
    enviroment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
  

  frontend:
    build: ./frontend
    container_name: openrag-frontend
    ports:
      - "8888:80"
    depends_on:
      - backend
