version: '3.8'

services:
  backend:
    build: ./backend
    container_name: openrag_backend
    restart: always
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  frontend:
    build: ./frontend
    container_name: openrag_frontend
    restart: always
    ports:
      - "8888:80"
    depends_on:
      - backend